### ISSUE TITLE
Consider keeping focus on audio management

### ISSUE THREAD

**Issue by Madis0** [ImUrX/LittleTweaks#1]
There are several mods that provide "random tweaks" in Curseforge already. As the name and featureset is vague, these mods are hard to find, don't get very popular and may include unexpected features in the future.

Consider keeping your focus and adding-improving only audio-related features here. If it grows into a bigger mod that does more relevant things (e.g. more volume sliders, more subtitles etc), that's fine, but adding new items and mobs for example would seem out of place.   

That said, maybe rename the mod as well.

**Comment by ImUrX** [comment]
I thought the mod more of client-side tweaks, nothing that will add new things or mobs, just things that make the experience of the current client better. That's why I called it little

One that I wanted to add but seems I need to use JNI is screenshots get pasted into clipboard but it's an example I want to give.

Another hope of mine is that the features in here will someday appear in vanilla but it's not something I expect

**Comment by Madis0** [comment]
Fair enough, consider then adding toggles for the different features as well (if they don't already exist), so users and modpacks can keep the features they need.

**Comment by ImUrX** [comment]
Yep, if I get the opportunity to implement another tweak i will
